FROM debian:10.2

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ \
        gfortran \
        bzip2 \
        unzip \
        make \
        wget \
        git \
        python3 \
        python3-dev \
        python3-websockets \
        python3-setuptools \
        zlib1g-dev \
        patch \
        ca-certificates \
        swig \
        cmake \
    && rm -rf /var/lib/apt/lists/*

RUN \
    git clone -b lookahead --single-branch https://github.com/alphacep/kaldi /opt/kaldi \
    && cd /opt/kaldi/tools \
    && sed -i 's:status=0:exit 0:g' extras/check_dependencies.sh \
    && sed -i 's:openfst_add_CXXFLAGS = -g -O2:openfst_add_CXXFLAGS = -g -O3 -msse2:g' Makefile \
    && sed -i 's:--enable-ngram-fsts:--enable-ngram-fsts --disable-bin:g' Makefile \
    && sed -i 's:python:python3:g' extras/install_openblas.sh \
    && sed -i 's:USE_LOCKING=1:TARGET=ATOM USE_LOCKING=1:g' extras/install_openblas.sh \
    && make -j $(nproc) openfst cub \
    && extras/install_openblas.sh \
    && cd /opt/kaldi/src \
    && ./configure --mathlib=OPENBLAS --shared \
    && sed -i 's:-msse -msse2:-msse -msse2:g' kaldi.mk \
    && sed -i 's: -O1 : -O3 :g' kaldi.mk \
    && make -j $(nproc) online2

RUN \
    git clone https://github.com/alphacep/vosk-api /opt/vosk-api \
    && sed -i 's:--max-active=3000:--max-active=7000:g' /opt/vosk-api/src/model.cc \
    && sed -i 's:--beam=10.0:--beam=13.0:g' /opt/vosk-api/src/model.cc \
    && sed -i 's:--lattice-beam=2.0:--lattice-beam=6.0:g' /opt/vosk-api/src/model.cc \
    && cd /opt/vosk-api/python \
    && KALDI_ROOT=/opt/kaldi python3 ./setup.py install --user --single-version-externally-managed --root=/ \
    && git clone https://github.com/alphacep/vosk-server /opt/vosk-server \
    && rm -rf /opt/kaldi

ENV MODEL_VERSION 0.1
RUN mkdir /opt/kaldi-en \
   && cd /opt/kaldi-en \
   && wget -q http://alphacephei.com/kaldi/kaldi-en-us-aspire-${MODEL_VERSION}.tar.gz \
   && tar xf kaldi-en-us-aspire-${MODEL_VERSION}.tar.gz \
   && mv kaldi-en-us-aspire-${MODEL_VERSION} model \
   && rm -rf kaldi-en-us-aspire-${MODEL_VERSION}.tar.gz

EXPOSE 2700
WORKDIR /opt/vosk-server/websocket
CMD [ "python3", "./asr_server.py", "/opt/kaldi-en/model" ]
