FROM debian:9.8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ \
        make \
        automake \
        autoconf \
        bzip2 \
        unzip \
        wget \
        libtool \
        git \
        subversion \
        sox \
        python2.7 \
        python3 \
        python3-dev \
        python3-websockets \
        pkg-config \
        zlib1g-dev \
        patch \
        libatlas-dev \
        ca-certificates \
        swig \
        libatlas3-base && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/kaldi-asr/kaldi.git /opt/kaldi && \
    cd /opt/kaldi && \
    cd /opt/kaldi/tools && \
    make -j $(nproc) && \
    cd /opt/kaldi/src && \
    ./configure --mathlib=ATLAS --shared && \
    make depend -j $(nproc) && \
    make -j $(nproc) online2 && \
    find /opt/kaldi -name "*.o" | xargs rm

RUN mkdir /opt/kaldi-websocket \
   && cd /opt/kaldi-websocket \
   && git clone https://github.com/alphacep/kaldi-websocket-python \
   && cd kaldi-websocket-python \
   && KALDI_ROOT=/opt/kaldi make \
   && cd /opt/kaldi/src \
   && make clean

ENV MODEL_VERSION 0.1
RUN mkdir /opt/kaldi-de \
   && cd /opt/kaldi-de \
   && wget http://ltdata1.informatik.uni-hamburg.de/kaldi_tuda_de/de_400k_nnet3chain_tdnn1f_2048_sp_bi.tar.bz2 \
   && tar xf de_400k_nnet3chain_tdnn1f_2048_sp_bi.tar.bz2 \
   && mkdir ivector \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/HCLG.fst . \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/final.mdl . \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/words.txt . \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/conf/mfcc_hires.conf mfcc.conf \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/phones/word_boundary.int . \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/ivector_extractor/final.dubm ivector \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/ivector_extractor/final.ie ivector \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/ivector_extractor/final.mat ivector \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/ivector_extractor/global_cmvn.stats ivector \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/ivector_extractor/splice.conf ivector \
   && mv de_400k_nnet3chain_tdnn1f_2048_sp_bi/ivector_extractor/online_cmvn.conf ivector \
   && rm -rf de_400k_nnet3chain_tdnn1f_2048_sp_bi \
   && rm -rf de_400k_nnet3chain_tdnn1f_2048_sp_bi.tar.bz2

EXPOSE 2700
WORKDIR /opt/kaldi-websocket/kaldi-websocket-python
CMD [ "python3", "./asr_server.py", "/opt/kaldi-de" ]
