FROM alphacep/kaldi-vosk-server-atom:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3-pip python3-wheel \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install wheel grpcio grpcio-tools \
    && cd /opt/vosk-server/grpc \
    && python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. stt_service.proto

ENV MODEL_VERSION 0.2
RUN mkdir /opt/vosk-model-en \
   && cd /opt/vosk-model-en \
   && wget -q http://alphacephei.com/kaldi/models/vosk-model-en-us-aspire-${MODEL_VERSION}.zip \
   && unzip vosk-model-en-us-aspire-${MODEL_VERSION}.zip \
   && mv vosk-model-en-us-aspire-${MODEL_VERSION} model \
   && rm -rf vosk-model-en-us-aspire-${MODEL_VERSION}.zip

EXPOSE 5001
WORKDIR /opt/vosk-server/grpc
CMD [ "python3", "./stt_server.py", "/opt/vosk-model-en/model" ]
